<?php
/**
 * @file
 * A description of what your module does.
 */
/**
 * Implements hook_menu().
 */
function product_menu() {
  $items = array();
  /**
   * Page shows products add form
   */
  $items['product/add'] = array(
    'title' => 'Product add',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('product_page_form'),
    'access callback' => TRUE,
  );
  /**
   * Product list page
   */
  $items['product/list'] = array(
    'title' => 'Product list',
    'page callback' => 'product_list_table',
    'access callback' => TRUE,
  );
  return $items;
}

function product_list_table() {
  $header = array(
    t('№'),
    t('Name'),
    t('Category'),
    t('Expiry'),
    t('Email'),
    t('Telephone'),
    t('Options')
  );
  $rows = array();
  $query = db_select('my_table', 't')
    ->fields('t', array(
      'number',
      'name',
      'category',
      'expiry',
      'email',
      'telephone'
    ))
    -> extend('PagerDefault')
    ->limit(5)
    ->execute();
  while ($value = $query->fetchAssoc()) {
    $rows[] = array(
      $value['number'],
      $value['name'],
      $value['category'],
      $value['expiry'],
      $value['email'],
      $value['telephone'],
      $form['google_link']['#markup']=l('Eit','http://google.com').(' / '). l('Delete','http://google.com') ,
    );
  }
  return array(
    array(
      '#theme' => 'table',
      '#header' => $header,
      '#rows' => $rows),
    array(
      '#theme' => 'pager',
      '#quantity' => 7,)
  );
}

function product_page_form($form, $form_state) {
  $form = array();
  $form['number'] = array(
    '#type' => 'textfield',
    '#title' => '№',
    '#size' => '4',
    '#required' => 'TRUE',
  );
  $form ['name'] = array(
    '#type' => 'textfield',
    '#title' => 'Enter product name',
    '#size' => '20',
    '#required' => 'TRUE',
  );
  $form ['category'] = array(
    '#title' => 'Choose the type of product',
    '#type' => 'select',
    '#options' => array(
      'Dishes' => 'Dishes',
      'Groceries' => 'Groceries',

    ),
  );
  $form ['expiry'] = array(
    '#title' => 'Enter the expiry date for product',
    '#type' => 'date',
    '#size' => '20',
    '#states' => array(
      'visible' => array(
        ':input[name = "category"]' => array('value' => 'Groceries'),
      ),
    ),
  );
  $form ['email'] = array(
    '#type' => 'textfield',
    '#title' => 'Email',
    '#size' => '20',
    '#required' => 'TRUE',
  );
  $form ['telephone'] = array(
    '#type' => 'textfield',
    '#title' => 'Enter phone number',
    '#size' => '20',
    '#required' => 'TRUE',
  );
  $form ['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );
  //$form ['list'] = '<a href="http://localhost/drupal_goods/product/list"> LIST </a>'; //Тестовая ссылка в форме

  $form['#submit'][] = 'my_table_insert_form_submit';
  $form['submit']['#validate'][] = 'product_email_validate';
  //$form['submit']['#validate'][] = 'product_date_validate';
  return $form;
}

function my_table_insert_form_submit($form, $form_state) {
  $query = db_insert('my_table')
    ->fields(array(
      'number' => $form_state['values']['number'],
      'name' => $form_state['values']['name'],
      'category' => $form_state['values']['category'],
      //    'expiry' => $form_state['values']['expiry'],
      'email' => $form_state['values']['email'],
      'telephone' => $form_state['values']['telephone'],
    ))
    ->execute();
  if ($query > 0) {
    drupal_set_message('Data successfully load');
  }
  else {
    drupal_set_message(t("Data hasn't been sent."), 'error');
  }
}





function product_email_validate($form, &$form_state) {
  $mail = $form_state['values']['email'];
  if (!valid_email_address($mail)) {
    form_set_error('email', t('Please Enter a valid email address.'));
  }}
/*
 * function product_date_validate($element) {
  if (!checkdate($element['#value']['month'], $element['#value']['day'], $element['#value']['year'])) {
    form_error($element, t('The specified date is invalid. Please change it to correct date'));
  }
}
 */