<?php
/**
 * @file
 * A description of what your module does.
 */
/**
 * Implements hook_menu().
 */
function product_menu() {
  $items = array();
  $items['product/add'] = array(
    'title' => 'Add product',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('product_page_form'),
    'access callback' => TRUE,
  );
  return $items;
}

function product_page_form($form, $form_state) {
  $form = array();

  $form['number'] = array(
    '#type' => 'textfield',
    '#title' => '№',
    '#size' => '4',
    '#required' => 'TRUE',
  );

  $form ['name'] = array(
    '#type' => 'textfield',
    '#title' => 'Enter product name',
    '#size' => '20',
    '#required' => 'TRUE',
  );

  $form ['category'] = array(
    '#title' => 'Choose the type of product',
    '#type' => 'select',
    '#options' => array(0 => ('Groceries'), 1 => ('Dishes')),
  );
  /**
  $form ['expiry'] = array(
    '#title' => 'Enter the expiry date for product',
    '#type' => 'date',
    '#size' => '20',
    '#states' => array(
      'visible' => array(
        ':input[name ="category"]' => array('value' => 0),
      ),
    ),
  );
  $form ['email'] = array(
    '#type' => 'textfield',
    '#title' => 'Email',
    '#size' => '20',
    '#required' => 'TRUE',
  );
  $form ['telephone'] = array(
    '#type' => 'textfield',
    '#title' => 'Enter phone number',
    '#size' => '20',
    '#required' => 'TRUE',
  );

*/
  $form ['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );
  $form['#submit'][] = 'my_table_insert_form_submit';

  return $form;
}

function my_table_insert_form_submit($form, $form_state) {
  $query = db_insert('my_table1')
    ->fields(array(
      'number' => $form_state['values']['number'],
      'name' => $form_state['values']['name'],

     'category' => $form_state['values']['category'],
      /**
      'expiry' => $form_state['values']['expiry'],
      'email' => $form_state['values']['email'],
      'telephone' => $form_state['values']['telephone'],
**/
    ))
    ->execute();
  if ($query > 0){
    drupal_set_message('Data succesfully load');
  }
  else {
    drupal_set_message(t("Data hasn't been sent."), 'error');
  }
}